---
title: "Introduction to R and RStudio"
subtitle: Instituto Nacional de Medicina Genomica
author:
  - __Daniel Rivas__
  - __Juan Manuel Mejia Arangure__
output:
  pdf_document: default
  html_document: default
---

# Learning Outcomes

Upon completion of this module, you should be able to:

- Work different data structures commonly used in R.
- Import and export data from and to R environment.
- Manipulate data.
- Visualize data & generate graphics.
- Install R packages.

# Course Overview

## R Basics

Regardless of the programming language you use, all share some commonalities. For example, you’ll likely need to perform basic operations on different data types, like applying mathematical equations to numeric data. You’ll also need an environment in which to write your code, and most modern integrated development environments (or IDEs) provide features that make writing code easier, like syntax checking, color coding, and integrated help. This module introduces you to the R language, its common data types, and techniques for manipulating them. You’ll also learn about the role of the R interpreter and how it transforms code into executable objects. Finally, you’ll be introduced the most common IDEs for R development: RStudio.

## R Programming Fundamentals

The R language supports many types of data structures that you can use to organize and store values in your code, including vectors, factors, lists, arrays, matrices, and data frames. Each data structure type serves a specific purpose and can contain specific kinds of data. So, it’s important to understand the differences between them so you can make the right choice based on your scenario. In this module, you’ll learn about the types of data you can store in each data structure and how to add, remove, or manipulate its contents.

## Working with Data

Data is everywhere! The data you need to analyze may come from a traditional database, but it may also come from a variety of different sources and systems, and it may come to you in one or more formats. For example, your data might be in text, Excel, .JSON, or .XML files. Or it may not be stored in a file at all, but instead lives on the pages of a website. How will you take all these different file formats and load them into your R working environment? This module provides you with the tools you need to read data from some common file formats and sources into data objects that you can then use and combine with other data objects in your data analysis.
